package com.gongdi.wordcards;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.ContentValues;
import android.content.Intent;
import android.content.SharedPreferences;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.Editable;
import android.text.InputType;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.view.WindowManager;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/** Android UI for local vocabulary, batch import, AI scene clustering and review. */
public class MainActivity extends Activity {
    private final int green=Color.rgb(43,92,84), ink=Color.rgb(28,41,40), paper=Color.rgb(247,247,243), muted=Color.rgb(103,116,112);
    private SQLiteDatabase db; private DataStore store; private KeyVault vault;
    private LinearLayout body; private SharedPreferences prefs; private JSONArray profiles;
    private String active="默认", tab="import"; private boolean busy=false;
    private final ExecutorService worker=Executors.newSingleThreadExecutor();

    @Override public void onCreate(Bundle state){super.onCreate(state);prefs=getSharedPreferences("api_profiles",MODE_PRIVATE);vault=new KeyVault(this);try{
        db=openOrCreateDatabase("words.db",MODE_PRIVATE,null);store=new DataStore(db);
        profiles=new JSONArray(prefs.getString("profiles","[]"));if(profiles.length()==0)profiles.put(new JSONObject().put("name","默认").put("base","https://api.openai.com/v1").put("model","gpt-4.1-mini").put("responses",true));
        active=prefs.getString("active","默认");if(profile(active)==null)active=profiles.getJSONObject(0).getString("name");home();
    }catch(Exception e){new AlertDialog.Builder(this).setTitle("无法打开词库").setMessage("迁移或读取本地数据失败。请不要卸载应用，以免丢失旧数据。").setPositiveButton("关闭",(d,w)->finish()).show();}}

    private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private TextView text(LinearLayout p,String s,int z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(0,dp(5),0,dp(7));t.setTextIsSelectable(true);p.addView(t);return t;}
    private TextView title(LinearLayout p,String s,int z){TextView t=text(p,s,z,ink);t.setTypeface(null,Typeface.BOLD);return t;}
    private Button button(LinearLayout p,String s,boolean primary,Runnable action){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTextColor(primary?Color.WHITE:green);b.setBackground(bg(primary?green:Color.rgb(231,238,231),12));b.setMinHeight(dp(50));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(6),0,dp(6));p.addView(b,lp);b.setOnClickListener(v->action.run());return b;}
    private EditText input(LinearLayout p,String label,String value,boolean multi){text(p,label,13,muted);EditText e=new EditText(this);e.setText(value);e.setTextSize(16);e.setTextColor(ink);e.setSingleLine(!multi);e.setGravity(multi?Gravity.TOP:Gravity.CENTER_VERTICAL);e.setMinLines(multi?6:1);e.setInputType(InputType.TYPE_CLASS_TEXT|(multi?InputType.TYPE_TEXT_FLAG_MULTI_LINE:InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS));e.setPadding(dp(12),dp(12),dp(12),dp(12));e.setBackground(bg(Color.rgb(239,243,239),10));p.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
    private LinearLayout card(){LinearLayout c=column();c.setPadding(dp(18),dp(16),dp(18),dp(16));c.setBackground(bg(Color.WHITE,18));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(12),0,dp(8));body.addView(c,lp);return c;}
    private void message(String s){new AlertDialog.Builder(this).setTitle("情境词卡").setMessage(s).setPositiveButton("知道了",null).show();}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}private String today(){return LocalDate.now().toString();}

    private void page(String section,String heading,String sub){getWindow().clearFlags(WindowManager.LayoutParams.FLAG_SECURE);tab=section;LinearLayout root=column();root.setBackgroundColor(paper);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i;});
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(18),dp(5),dp(18),0);TextView logo=new TextView(this);logo.setText("◫ 情境词卡");logo.setTextColor(green);logo.setTypeface(null,Typeface.BOLD);logo.setTextSize(19);logo.setGravity(Gravity.CENTER_VERTICAL);top.addView(logo,new LinearLayout.LayoutParams(0,dp(50),1));Button settings=new Button(this);settings.setText("API 设置");settings.setAllCaps(false);settings.setTextColor(green);settings.setOnClickListener(v->settings(active));top.addView(settings);root.addView(top);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);body=column();body.setPadding(dp(18),dp(10),dp(18),dp(22));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));title(body,heading,28);text(body,sub,14,muted);
        LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(8),dp(4),dp(8),dp(5));String[] labels={"＋ 导入","▦ 场景","▤ 单词本","✓ 复习"};String[] tabs={"import","scenes","words","review"};for(int i=0;i<4;i++){final int x=i;Button b=new Button(this);b.setText(labels[i]);b.setAllCaps(false);b.setTextSize(13);b.setTextColor(section.equals(tabs[i])?Color.WHITE:green);b.setBackground(bg(section.equals(tabs[i])?green:paper,11));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(51),1);lp.setMargins(dp(2),0,dp(2),0);nav.addView(b,lp);b.setOnClickListener(v->{if(x==0)home();else if(x==1)scenesHome();else if(x==2)library();else review();});}root.addView(nav);setContentView(root);root.requestApplyInsets();}

    private ArrayList<JSONObject> rows(){ArrayList<JSONObject> out=new ArrayList<>();try(Cursor c=db.rawQuery("SELECT word,content,stage,due,mastery,learned_at FROM words ORDER BY word",null)){while(c.moveToNext())out.add(new JSONObject().put("word",c.getString(0)).put("content",new JSONObject(c.getString(1))).put("stage",c.getInt(2)).put("due",c.getString(3)).put("mastery",c.getInt(4)).put("learned_at",c.isNull(5)?"":c.getString(5)));}catch(Exception e){message("词库读取失败。");}return out;}
    private JSONObject find(String w){for(JSONObject r:rows())if(w.equals(r.optString("word")))return r;return null;}private int dueCount(){int n=0;for(JSONObject r:rows())if(!r.optString("learned_at").isEmpty()&&r.optString("due").compareTo(today())<=0)n++;return n;}

    private void home(){page("import","批量导入单词","无需选择场景，AI 会从整批单词中自动发现情境。");text(body,rows().size()+" 个单词 · 今天待复习 "+dueCount()+" 个",16,green);
        long draft=store.latestBatch();if(draft>0){LinearLayout resume=card();title(resume,"有未完成的导入",20);text(resume,"上次的解析或分类结果已保存，不会自动重新调用 AI。",14,muted);button(resume,"继续上次导入",true,()->resumeBatch(draft));try{if(store.debugResponses(draft).length()>0)button(resume,"查看 AI 调试返回",false,()->debugResponsesPage(draft));}catch(Exception ignored){}}
        LinearLayout c=card();EditText raw=input(c,"每行一个单词，也可写成 word: 释义","",true);raw.setHint("boarding pass: 登机牌\ncheck in\npassport, 护照");button(c,"预览粘贴内容",true,()->parsePreview(raw.getText().toString(),false,"paste"));button(c,"选择 CSV 文件",false,()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/*");startActivityForResult(i,20);});
        text(c,"支持空行、重复项、制表符、冒号、等号和 CSV 前两列。导入前不会写入词库。",13,muted);button(body,"单独手动添加",false,()->manual(""));}

    private void parsePreview(String raw,boolean csv,String source){try{JSONObject p=ImportParser.parse(raw,csv);JSONArray items=p.getJSONArray("items"),kept=new JSONArray(),existing=new JSONArray();for(int i=0;i<items.length();i++){JSONObject item=items.getJSONObject(i);if(find(item.getString("word"))!=null)existing.put(item);else kept.put(item);}p.put("items",kept).put("existing",existing);showImportPreview(p,source);}catch(Exception e){message("解析失败："+e.getMessage());}}
    private void showImportPreview(JSONObject p,String source)throws Exception{page("import","导入预览","检查有效单词、重复项和格式错误，再交给 AI 整批分析。");JSONArray items=p.getJSONArray("items"),existing=p.getJSONArray("existing"),errors=p.getJSONArray("errors"),dups=p.getJSONArray("duplicates");LinearLayout ok=card();title(ok,"可导入 "+items.length()+" 个",20);for(int i=0;i<items.length();i++){JSONObject x=items.getJSONObject(i);text(ok,x.getString("word")+(x.optString("meaning").isEmpty()?"":" — "+x.optString("meaning")),15,ink);}LinearLayout issues=card();title(issues,"已处理的问题",20);text(issues,"已有词 "+existing.length()+" · 本批重复 "+dups.length()+" · 格式问题 "+errors.length()+" · 空行 "+p.optInt("empty_lines"),14,muted);for(int i=0;i<errors.length();i++){JSONObject e=errors.getJSONObject(i);text(issues,"第 "+e.optInt("line")+" 行："+e.optString("message")+" — "+e.optString("raw"),13,Color.rgb(150,67,46));}if(items.length()>0)button(body,"确认列表并让 AI 分类",true,()->{try{long id=store.createBatch(p,source);classifyBatch(id,false);}catch(Exception e){message("保存导入批次失败："+e.getMessage());}});button(body,"返回修改",false,()->home());}
    private void resumeBatch(long id){if("parsed".equals(store.batchStatus(id)))classifyBatch(id,false);else classificationPreview(id);}

    private void classifyBatch(long id,boolean reclassify){if(busy){message("已有 AI 任务正在运行。");return;}JSONObject p=profile(active);String key=vault.get(active);if(p==null||key.isEmpty()){message("请先在 API 设置中填写并验证密钥。导入批次已经保存，设置后可继续。");settings(active);return;}if(reclassify)new AlertDialog.Builder(this).setTitle("重新分类？").setMessage("会调用 AI 并替换本批次现有分类和人工调整。旧单词及复习记录不会删除。").setNegativeButton("取消",null).setPositiveButton("重新分类",(d,w)->runClassification(id,p,key,true)).show();else runClassification(id,p,key,false);}
    private void runClassification(long id,JSONObject p,String key,boolean restart){busy=true;home();toast("AI 正在分组分析单词，请稍候。");worker.execute(()->{try{if(restart)store.clearChunks(id);JSONArray all=store.batchItems(id),known=store.knownWordsExcluding(all,300),sceneNames=store.existingSceneNames(200);JSONObject total=ApiClient.emptyClassification();int size=30,groups=(all.length()+size-1)/size;for(int group=0;group<groups;group++){final int shown=group+1;runOnUiThread(()->toast("正在分析第 "+shown+" / "+groups+" 组"));JSONArray chunk=new JSONArray();for(int i=group*size;i<Math.min(all.length(),(group+1)*size);i++)chunk.put(all.getJSONObject(i));JSONObject part=store.loadChunk(id,group);if(part==null){String raw="";try{raw=ApiClient.generateBatchRaw(chunk,known,sceneNames,p.getString("base"),p.getString("model"),key,p.optBoolean("responses"));part=ApiClient.parseEnvelope(raw,p.optBoolean("responses"));int dropped=store.sanitizeLinks(part,chunk,all);store.validateClassification(part,chunk);store.saveDebugResponse(id,group,dropped>0?"有效，已忽略 "+dropped+" 条无效关联":"有效",redactSecret(raw,key));store.saveChunk(id,group,part);}catch(Exception problem){store.saveDebugResponse(id,group,"失败",debugFailureContent(raw,problem,key));throw problem;}}else{int dropped=store.sanitizeLinks(part,chunk,all);store.validateClassification(part,chunk);if(dropped>0){store.saveChunk(id,group,part);store.saveDebugResponse(id,group,"缓存修复，已忽略 "+dropped+" 条无效关联",part.toString(2));}}ApiClient.mergeClassification(total,part);JSONArray scenes=part.getJSONArray("scenes");for(int i=0;i<scenes.length();i++){String name=scenes.getJSONObject(i).getString("name");boolean exists=false;for(int j=0;j<sceneNames.length();j++)if(name.equals(sceneNames.getString(j))){exists=true;break;}if(!exists)sceneNames.put(name);}}store.saveClassification(id,total);store.clearChunks(id);runOnUiThread(()->{busy=false;classificationPreview(id);});}catch(Exception e){runOnUiThread(()->{busy=false;if(e.getMessage()!=null&&e.getMessage().startsWith("HTTP 401"))vault.clear(active);home();message(safeError(e)+"\n\n已完成的分组已经缓存，点击“继续上次导入”会从未完成处继续。也可以点击“查看 AI 调试返回”检查原始内容。");});}});}

    private void debugResponsesPage(long batchId){page("import","AI 调试返回","按时间保存每次分类接口的原始返回和本地校验结果；不保存请求内容或 API Key。");try{JSONArray logs=store.debugResponses(batchId);if(logs.length()==0){text(card(),"这个批次还没有可查看的返回记录。",15,muted);}for(int i=0;i<logs.length();i++){JSONObject log=logs.getJSONObject(i);LinearLayout c=card();title(c,"第 "+(log.getInt("chunk")+1)+" 组 · "+log.getString("status"),18);text(c,log.getString("received_at").replace('T',' '),13,muted);TextView raw=text(c,log.getString("content"),12,ink);raw.setTypeface(Typeface.MONOSPACE);raw.setTextIsSelectable(true);}button(body,"返回导入",false,()->home());}catch(Exception e){message("调试记录读取失败："+e.getMessage());}}
    private String redactSecret(String content,String secret){if(content==null)return"";return secret==null||secret.isEmpty()?content:content.replace(secret,"***");}
    private String debugFailureContent(String raw,Exception problem,String key){if(!raw.isEmpty())return redactSecret(raw,key)+"\n\n[本地解析或校验]\n"+safeError(problem);String response=ApiClient.responseBody(problem);return response.isEmpty()?safeError(problem):redactSecret(response,key)+"\n\n[HTTP 错误]\n"+safeError(problem);}
    private boolean causedBy(Throwable error,Class<?> type){for(Throwable current=error;current!=null;current=current.getCause())if(type.isInstance(current))return true;return false;}
    private String safeError(Exception e){
        if(causedBy(e,java.net.UnknownHostException.class))return"手机无法解析 API 域名。请检查 Base URL 拼写、手机 DNS，或确认手机本身能访问该服务商。电脑上的代理不会自动给手机使用。";
        if(causedBy(e,javax.net.ssl.SSLHandshakeException.class)||causedBy(e,javax.net.ssl.SSLException.class))return"API 的 HTTPS 证书校验失败。请使用证书有效的 HTTPS 地址，不要使用自签名证书或被代理替换证书的地址。";
        if(causedBy(e,java.net.NoRouteToHostException.class)||causedBy(e,java.net.ConnectException.class))return"手机无法连接到 API 服务器。请确认服务商在当前手机网络可访问；如果服务需要代理或 VPN，需要在手机上启用。";
        if(causedBy(e,java.net.SocketTimeoutException.class))return"API 连接或生成超时。请检查手机网络后重试；导入批次和原分类没有丢失。";
        if(e instanceof java.io.IOException)return"手机网络连接在请求过程中中断。请切换 Wi-Fi/移动网络后重试，并确认 API 地址能由手机直接访问。";
        return e.getMessage()==null?"AI 返回内容无法验证，未覆盖现有结果。":e.getMessage();
    }

    private void scenesHome(){page("scenes","全部场景","直接查看各个场景。默认收起，展开后显示单词、理由以及 AI 对联系和区别的总结。");try{JSONArray scenes=store.allScenes();if(scenes.length()==0){text(card(),"还没有场景。先批量导入一组单词，让 AI 从整体关系中聚类。",15,muted);return;}for(int i=0;i<scenes.length();i++){JSONObject scene=scenes.getJSONObject(i);LinearLayout c=card(),details=column();JSONArray members=scene.getJSONArray("members");Button toggle=button(c,"＋ "+scene.getString("name")+" · "+members.length()+" 个词",false,()->{});c.addView(details);details.setVisibility(View.GONE);toggle.setOnClickListener(v->{boolean open=details.getVisibility()!=View.VISIBLE;details.setVisibility(open?View.VISIBLE:View.GONE);toggle.setText((open?"－ ":"＋ ")+scene.optString("name")+" · "+members.length()+" 个词");});for(int j=0;j<members.length();j++){JSONObject member=members.getJSONObject(j);text(details,member.getString("word")+(member.optString("meaning").isEmpty()?"":" · "+member.optString("meaning"))+"\n"+member.optString("reason"),14,ink);}JSONObject summary=store.sceneSummary(scene.getString("name"),scene.getString("fingerprint"));if(summary==null){text(details,"这个场景还没有 AI 总结。生成后会保存在本地，成员不变时不会重复调用。",13,muted);button(details,"生成联系、区别和记忆路线",true,()->generateSceneSummary(scene));}else{renderSceneSummary(details,summary);button(details,"重新生成 AI 总结",false,()->generateSceneSummary(scene));button(details,"查看总结原始返回",false,()->showSceneRaw(summary.optString("_raw")));}button(details,"编辑这个场景的分类",false,()->classificationPreview(scene.optLong("batch_id")));}}catch(Exception e){message("无法读取场景列表："+e.getMessage());}}
    private void renderSceneSummary(LinearLayout parent,JSONObject summary){title(parent,"AI 场景总结",18);String[] fields={"overview","connections","differences","memory_path"},labels={"整体情境","单词之间的联系","容易混淆的区别","串联记忆路线"};for(int i=0;i<fields.length;i++){text(parent,labels[i],13,green);text(parent,summary.optString(fields[i]),15,ink);}}
    private void showSceneRaw(String raw){page("scenes","AI 场景总结原始返回","内容已脱敏，可用于调试接口和总结格式。");LinearLayout c=card();TextView value=text(c,raw,12,ink);value.setTypeface(Typeface.MONOSPACE);value.setTextIsSelectable(true);button(body,"返回全部场景",true,()->scenesHome());}
    private void generateSceneSummary(JSONObject scene){if(busy){message("已有 AI 请求正在运行。");return;}JSONObject p=profile(active);String key=vault.get(active);if(p==null||key.isEmpty()){message("生成场景总结需要 API 密钥，请先完成 API 设置。");settings(active);return;}busy=true;toast("AI 正在总结场景内单词的联系与区别…");worker.execute(()->{String raw="";try{raw=ApiClient.sceneSummaryRaw(scene,p.getString("base"),p.getString("model"),key,p.optBoolean("responses"));JSONObject summary=ApiClient.parseSceneSummary(raw,p.optBoolean("responses"));store.saveSceneSummary(scene.getString("name"),scene.getString("fingerprint"),summary,redactSecret(raw,key));runOnUiThread(()->{busy=false;scenesHome();toast("场景总结已保存，展开场景即可查看。");});}catch(Exception e){runOnUiThread(()->{busy=false;message("场景总结失败："+safeError(e));});}});}
    private void classificationPreview(long id){page("scenes","分类预览","可重命名、移动、合并或拆分。人工调整会立即保存。");try{JSONArray scenes=store.batchScenes(id);HashMap<String,Integer> counts=new HashMap<>();for(int i=0;i<scenes.length();i++){JSONArray ms=scenes.getJSONObject(i).getJSONArray("members");for(int j=0;j<ms.length();j++){String w=ms.getJSONObject(j).getString("word");counts.put(w,counts.containsKey(w)?counts.get(w)+1:1);}}
        for(int i=0;i<scenes.length();i++){JSONObject scene=scenes.getJSONObject(i);long sid=scene.getLong("id");LinearLayout c=card();title(c,scene.getString("name"),21);JSONArray members=scene.getJSONArray("members");for(int j=0;j<members.length();j++){JSONObject m=members.getJSONObject(j);text(c,m.getString("word")+(counts.get(m.getString("word"))>1?" · 多场景":"")+"\n"+m.getString("reason"),14,ink);}button(c,"修改场景",false,()->editScene(id,sid));}
        JSONArray missing=store.unclassified(id);if(missing.length()>0){LinearLayout c=card();title(c,"无法准确判断",20);for(int i=0;i<missing.length();i++){JSONObject x=missing.getJSONObject(i);text(c,x.getString("word")+" — "+x.optString("reason"),14,ink);}}
        if("draft".equals(store.batchStatus(id)))button(body,"确认并保存分类",true,()->{store.confirm(id);toast("分类已确认，不会自动重算。");classificationPreview(id);});else text(body,"此分类已确认；人工调整仍会保存。",14,green);button(body,"查看 AI 调试返回",false,()->debugResponsesPage(id));button(body,"主动重新分类",false,()->classifyBatch(id,true));
    }catch(Exception e){message("分类读取失败："+e.getMessage());}}

    private void editScene(long batch,long sid){try{JSONArray scenes=store.batchScenes(batch);JSONObject current=null;for(int i=0;i<scenes.length();i++)if(scenes.getJSONObject(i).getLong("id")==sid)current=scenes.getJSONObject(i);if(current==null)return;final JSONObject chosen=current;String[] actions={"修改名称","移动一个单词","合并到其他场景","拆分出新场景"};new AlertDialog.Builder(this).setTitle(chosen.getString("name")).setItems(actions,(d,which)->{if(which==0)renameScene(batch,sid,chosen.optString("name"));else if(which==1)chooseMove(batch,chosen,scenes);else if(which==2)chooseMerge(batch,chosen,scenes);else splitScene(batch,chosen);}).show();}catch(Exception e){message("无法修改场景。");}}
    private void renameScene(long batch,long sid,String old){EditText e=new EditText(this);e.setText(old);new AlertDialog.Builder(this).setTitle("新场景名称").setView(e).setNegativeButton("取消",null).setPositiveButton("保存",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty()||n.length()>40){message("名称需为 1–40 个字符。");return;}store.renameScene(sid,n);classificationPreview(batch);}).show();}
    private void chooseMove(long batch,JSONObject from,JSONArray scenes){try{JSONArray members=from.getJSONArray("members");String[] words=new String[members.length()];for(int i=0;i<words.length;i++)words[i]=members.getJSONObject(i).getString("word");new AlertDialog.Builder(this).setTitle("选择要移动的单词").setItems(words,(d,wi)->{ArrayList<JSONObject> targets=new ArrayList<>();for(int i=0;i<scenes.length();i++)if(scenes.optJSONObject(i).optLong("id")!=from.optLong("id"))targets.add(scenes.optJSONObject(i));String[] names=new String[targets.size()];for(int i=0;i<names.length;i++)names[i]=targets.get(i).optString("name");new AlertDialog.Builder(this).setTitle("移动到").setItems(names,(d2,si)->{store.moveWord(from.optLong("id"),targets.get(si).optLong("id"),words[wi]);classificationPreview(batch);}).show();}).show();}catch(Exception e){message("移动失败。");}}
    private void chooseMerge(long batch,JSONObject from,JSONArray scenes){ArrayList<JSONObject> targets=new ArrayList<>();for(int i=0;i<scenes.length();i++)if(scenes.optJSONObject(i).optLong("id")!=from.optLong("id"))targets.add(scenes.optJSONObject(i));String[] names=new String[targets.size()];for(int i=0;i<names.length;i++)names[i]=targets.get(i).optString("name");new AlertDialog.Builder(this).setTitle("合并到哪个场景？").setItems(names,(d,i)->{store.mergeScene(from.optLong("id"),targets.get(i).optLong("id"));classificationPreview(batch);}).show();}
    private void splitScene(long batch,JSONObject from){LinearLayout box=column();box.setPadding(dp(20),0,dp(20),0);EditText name=input(box,"新场景名称","",false),words=input(box,"要移出的单词，用逗号分隔","",true);new AlertDialog.Builder(this).setTitle("拆分场景").setView(box).setNegativeButton("取消",null).setPositiveButton("拆分",(d,w)->{try{String n=name.getText().toString().trim();if(n.isEmpty())throw new Exception("请输入名称。");store.splitScene(from.optLong("id"),n,words.getText().toString().split("[,，\\s]+"));classificationPreview(batch);}catch(Exception e){message("拆分失败："+e.getMessage());}}).show();}

    private void library(){page("words","我的单词本","先学习词卡，再加入记忆曲线；未学习的词不会出现在复习中。");EditText search=input(body,"搜索单词、释义或场景","",false);LinearLayout list=column();body.addView(list);Runnable render=()->{list.removeAllViews();String q=search.getText().toString().trim().toLowerCase(java.util.Locale.ROOT);int count=0;for(JSONObject r:rows()){String w=r.optString("word"),m=r.optJSONObject("content").optString("meaning"),ss="";try{JSONArray s=store.scenesFor(w);for(int i=0;i<s.length();i++)ss+=s.getJSONObject(i).optString("name")+" ";}catch(Exception ignored){}if(!w.contains(q)&&!m.contains(q)&&!ss.toLowerCase(java.util.Locale.ROOT).contains(q))continue;count++;String state=r.optString("learned_at").isEmpty()?"未学习":r.optInt("mastery")==2?"已掌握":r.optInt("mastery")==1?"复习中 · 熟悉":"复习中";button(list,w+" · "+m+"\n"+state+(ss.isEmpty()?"":" · "+ss.trim()),false,()->detail(w,false));}if(count==0)text(list,q.isEmpty()?"还没有单词。":"没有匹配结果。",15,muted);};render.run();search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){render.run();}public void afterTextChanged(Editable e){}});button(body,"导出词库备份",false,()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"情境词卡-"+today()+".json");startActivityForResult(i,10);});button(body,"导入旧版词库备份",false,()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");startActivityForResult(i,11);});}
    private void manual(String initial){page("import","手动添加","手动录入不会自动创建场景，可稍后与一批新词一起分析。");LinearLayout c=card();EditText word=input(c,"英文单词或短语",initial,false),meaning=input(c,"中文意思","",true),example=input(c,"例句（选填）","",true);button(c,"保存",true,()->{try{String w=Review.normalize(word.getText().toString()),m=meaning.getText().toString().trim();if(m.isEmpty())throw new Exception("请填写中文意思。");if(find(w)!=null)throw new Exception("这个词已经存在。");JSONObject content=emptyCard(w,m);content.put("example",example.getText().toString().trim());ContentValues v=new ContentValues();v.put("word",w);v.put("content",content.toString());v.put("stage",0);v.put("due",today());db.insertOrThrow("words",null,v);detail(w,false);}catch(Exception e){message(e.getMessage());}});}
    private JSONObject emptyCard(String word,String meaning)throws Exception{JSONObject c=new JSONObject().put("word",word);for(String f:ApiClient.FIELDS)c.put(f,"");return c.put("meaning",meaning).put("quiz","“"+meaning+"”用英语怎么说？").put("answer",word);}

    private String openQuestion(String word){return"请不用照抄词卡，用自己的话解释 “"+word+"” 的核心含义，并写一个自然的英文例句。";}
    private void detail(String word,boolean reviewing){JSONObject row=find(word);if(row==null){library();return;}if(reviewing){page("review","开放式回忆","今天还有 "+dueCount()+" 个到期单词，按乱序逐个复习");String question=openQuestion(word);LinearLayout c=card();title(c,question,22);text(c,"可以用中文解释；英文例句要体现你对这个词的理解。提交后由 AI 评判并自动安排下次复习。",15,muted);EditText answer=input(c,"你的回答","",true);button(c,"提交给 AI 评判",true,()->{String typed=answer.getText().toString().trim();if(typed.isEmpty())message("请先输入你的解释和例句。");else judgeReview(word,row,question,typed);});button(c,"进入多轮 AI 互动检查",false,()->memoryCoach(word));}else showDetails(word,row);}
    private void showDetails(String word,JSONObject row){page("words",word,"先理解词义和用法，学完后再加入记忆曲线。");JSONObject content=row.optJSONObject("content");LinearLayout c=card();title(c,content.optString("meaning"),23);String[] fs={"part_of_speech","explanation","example","translation","memory","quiz"},ls={"词性","清晰解释","例句","翻译","记忆提示","开放式练习"};for(int i=0;i<fs.length;i++)if(!content.optString(fs[i]).isEmpty()){text(c,ls[i],13,green);text(c,content.optString(fs[i]),16,ink);}if(!content.optString("answer").isEmpty())button(c,"查看练习参考",false,()->message(content.optString("answer")));
        try{JSONArray scenes=store.scenesFor(word);if(scenes.length()>0){LinearLayout s=card();title(s,"所属场景",20);for(int i=0;i<scenes.length();i++){JSONObject x=scenes.getJSONObject(i);text(s,x.getString("name")+"\n"+x.optString("reason"),14,ink);}}JSONArray links=store.linksFor(word);if(links.length()>0){LinearLayout l=card();title(l,"连接已学单词",20);for(int i=0;i<links.length();i++){JSONObject x=links.getJSONObject(i);text(l,x.getString("old_word")+" · "+x.optString("relation")+"\n"+x.getString("reason")+"\n"+x.optString("example"),14,ink);}}}catch(Exception e){text(body,"场景或关联读取失败。",13,Color.RED);}
        button(body,"和 AI 互动检查记忆",true,()->memoryCoach(word));if(row.optString("learned_at").isEmpty())button(body,"学完，加入记忆曲线",false,()->startLearning(word));button(body,row.optInt("mastery")==2?"✓ 已掌握":"标记为已掌握",false,()->setMastery(word,2));button(body,"标记为熟悉",false,()->setMastery(word,1));button(body,"删除单词",false,()->new AlertDialog.Builder(this).setTitle("删除 "+word+"？").setMessage("会删除词卡、场景成员和关联，批次记录仍保留。").setNegativeButton("取消",null).setPositiveButton("删除",(d,w)->{db.beginTransaction();try{db.delete("scene_words","word=?",new String[]{word});db.delete("word_links","new_word=? OR old_word=?",new String[]{word,word});db.delete("words","word=?",new String[]{word});db.setTransactionSuccessful();}finally{db.endTransaction();}library();}).show());}
    private void startLearning(String word){ContentValues v=new ContentValues();v.put("learned_at",LocalDateTime.now().toString());v.put("stage",0);v.put("due",LocalDate.now().plusDays(1).toString());db.update("words",v,"word=? AND learned_at IS NULL",new String[]{word});toast("已加入记忆曲线，明天开始第一次复习。");detail(word,false);}
    private void setMastery(String word,int value){JSONObject row=find(word);ContentValues v=new ContentValues();v.put("mastery",value);if(row!=null&&row.optString("learned_at").isEmpty()){v.put("learned_at",LocalDateTime.now().toString());v.put("stage",0);v.put("due",LocalDate.now().plusDays(1).toString());}db.update("words",v,"word=?",new String[]{word});if(value==2){String next=nextUnmastered(word);if(next==null){toast("所有单词都已掌握。");library();}else{toast("已掌握，自动进入下一个。");detail(next,false);}}else{toast("已标记为熟悉并加入记忆曲线。");detail(word,false);}}
    private String nextUnmastered(String current){try(Cursor c=db.rawQuery("SELECT word FROM words WHERE mastery<2 AND word<>? ORDER BY CASE WHEN word>? THEN 0 ELSE 1 END,word LIMIT 1",new String[]{current,current})){return c.moveToFirst()?c.getString(0):null;}}
    private void memoryCoach(String word){JSONObject row=find(word);if(row==null){library();return;}page("words","AI 互动检查 · "+word,"AI 会从不同角度连续追问，并判断你是会主动回忆，还是只对答案眼熟。");try{JSONArray history=store.memoryTurns(word,6);int start=Math.max(0,history.length()-3);for(int i=start;i<history.length();i++){JSONObject turn=history.getJSONObject(i),result=turn.getJSONObject("result");LinearLayout h=card();title(h,"问题",15);text(h,turn.getString("question"),14,ink);title(h,"你的回答",15);text(h,turn.getString("answer"),14,ink);title(h,"AI："+result.optString("verdict")+" · "+result.optInt("score")+" 分",16);text(h,result.optString("feedback"),14,ink);text(h,result.optString("explanation"),14,muted);}JSONObject last=history.length()==0?null:history.getJSONObject(history.length()-1);String question=last==null?"不用查看词卡，请解释 “"+word+"” 的核心含义，并给出一个自然使用场景。":last.getJSONObject("result").optString("next_question",openQuestion(word));LinearLayout c=card();title(c,"下一题",19);text(c,question,16,green);EditText answer=input(c,"你的回答","",true);button(c,"发送给 AI",true,()->{String typed=answer.getText().toString().trim();if(typed.isEmpty())message("请先输入回答。");else sendMemoryTurn(word,row,history,question,typed);});if(last!=null){JSONObject result=last.getJSONObject("result");if(result.optBoolean("remembered"))button(body,"AI 判断已记住：标记熟悉并加入曲线",false,()->setMastery(word,1));button(body,"查看上一轮原始返回",false,()->showMemoryRaw(word,last.optString("raw")));}button(body,"返回词卡",false,()->detail(word,false));}catch(Exception e){message("互动记录读取失败："+e.getMessage());}}
    private void sendMemoryTurn(String word,JSONObject row,JSONArray history,String question,String answer){if(busy){message("已有 AI 请求正在运行。");return;}JSONObject p=profile(active);String key=vault.get(active);if(p==null||key.isEmpty()){message("互动检查需要 API 密钥，请先完成 API 设置。");settings(active);return;}JSONArray recent=new JSONArray();try{for(int i=Math.max(0,history.length()-4);i<history.length();i++){JSONObject turn=history.getJSONObject(i),result=turn.getJSONObject("result");recent.put(new JSONObject().put("question",turn.getString("question")).put("answer",turn.getString("answer")).put("score",result.optInt("score")).put("verdict",result.optString("verdict")));}}catch(Exception ignored){}busy=true;toast("AI 正在分析你的回忆…");worker.execute(()->{String raw="";try{raw=ApiClient.memoryCoachRaw(row.getJSONObject("content"),recent,question,answer,p.getString("base"),p.getString("model"),key,p.optBoolean("responses"));JSONObject result=ApiClient.parseMemoryCoach(raw,p.optBoolean("responses"));store.saveMemoryTurn(word,question,answer,result,redactSecret(raw,key));runOnUiThread(()->{busy=false;memoryCoach(word);});}catch(Exception e){String diagnostic=debugFailureContent(raw,e,key);try{store.saveMemoryTurn(word,question,answer,new JSONObject().put("score",0).put("remembered",false).put("verdict","请求失败").put("feedback",safeError(e)).put("explanation","本轮没有完成判断。").put("next_question",question),diagnostic);}catch(Exception ignored){}runOnUiThread(()->{busy=false;message("AI 互动失败："+safeError(e));});}});}
    private void showMemoryRaw(String word,String raw){page("words","AI 互动原始返回","内容已脱敏，可用于调试互动评判。");LinearLayout c=card();TextView value=text(c,raw,12,ink);value.setTypeface(Typeface.MONOSPACE);value.setTextIsSelectable(true);button(body,"返回互动检查",true,()->memoryCoach(word));}
    private void review(){try(Cursor c=db.rawQuery("SELECT word FROM words WHERE learned_at IS NOT NULL AND due<=? ORDER BY RANDOM() LIMIT 1",new String[]{today()})){if(c.moveToFirst()){detail(c.getString(0),true);return;}}page("review",rows().isEmpty()?"先导入一些单词吧":"今天没有到期复习","只有学完并加入记忆曲线的单词，才会在到期日出现在这里。");button(body,"去单词本学习",true,()->library());}
    private void judgeReview(String word,JSONObject row,String question,String answer){if(busy){message("已有 AI 请求正在运行。");return;}JSONObject p=profile(active);String key=vault.get(active);if(p==null||key.isEmpty()){message("AI 评判需要 API 密钥，请先完成 API 设置。");settings(active);return;}busy=true;toast("AI 正在评判你的回答…");worker.execute(()->{String raw="";try{raw=ApiClient.evaluateReviewRaw(row.getJSONObject("content"),question,answer,p.getString("base"),p.getString("model"),key,p.optBoolean("responses"));JSONObject result=ApiClient.parseReviewEvaluation(raw,p.optBoolean("responses"));int rating=result.getInt("rating");String[] next=Review.next(row.getInt("stage"),rating,LocalDate.now());ContentValues v=new ContentValues();v.put("stage",Integer.parseInt(next[0]));v.put("due",next[1]);int mastery=Math.max(row.optInt("mastery"),rating==1?(Integer.parseInt(next[0])>=4?2:1):0);v.put("mastery",mastery);String safeRaw=redactSecret(raw,key);db.beginTransaction();try{db.update("words",v,"word=? AND due=? AND stage=?",new String[]{word,row.getString("due"),row.getString("stage")});store.saveReviewAttempt(word,question,answer,result,safeRaw);db.setTransactionSuccessful();}finally{db.endTransaction();}String finalRaw=safeRaw;runOnUiThread(()->{busy=false;showReviewResult(word,row,question,answer,result,next[1],finalRaw);});}catch(Exception e){String diagnostic=debugFailureContent(raw,e,key);try{store.saveReviewAttempt(word,question,answer,new JSONObject().put("rating",3).put("verdict","评判失败").put("feedback",safeError(e)).put("explanation","未更新复习进度"),diagnostic);}catch(Exception ignored){}runOnUiThread(()->{busy=false;if(e.getMessage()!=null&&e.getMessage().startsWith("HTTP 401"))vault.clear(active);message("AI 评判失败："+safeError(e)+"\n\n本次不会更新记忆曲线，可以直接重试。");});}});}
    private void showReviewResult(String word,JSONObject row,String question,String answer,JSONObject result,String nextDue,String raw){page("review","AI 评判："+result.optString("verdict"),"下次复习："+nextDue+" · 剩余到期 "+dueCount()+" 个");LinearLayout a=card();title(a,"问题",16);text(a,question,15,ink);title(a,"你的回答",16);text(a,answer,15,ink);title(a,"具体反馈",18);text(a,result.optString("feedback"),16,ink);title(a,"清晰解释",18);text(a,result.optString("explanation"),16,ink);title(a,"示范回答",18);text(a,result.optString("suggested_answer"),16,green);JSONObject content=row.optJSONObject("content");title(a,word+" · "+content.optString("meaning"),20);text(a,content.optString("explanation"),16,ink);button(body,"继续下一个乱序复习",true,()->review());button(body,"针对这个词继续和 AI 互动",false,()->memoryCoach(word));button(body,"查看本次 AI 原始返回",false,()->showReviewRaw(raw));}
    private void showReviewRaw(String raw){page("review","AI 评判原始返回","内容已脱敏，可用于调试接口和评判格式。");LinearLayout c=card();TextView value=text(c,raw,12,ink);value.setTypeface(Typeface.MONOSPACE);value.setTextIsSelectable(true);button(body,"返回今日复习",true,()->review());}

    private JSONObject profile(String n){for(int i=0;i<profiles.length();i++){JSONObject p=profiles.optJSONObject(i);if(p!=null&&n.equals(p.optString("name")))return p;}return null;}private void persistProfiles(){prefs.edit().putString("profiles",profiles.toString()).putString("active",active).apply();}
    private void settings(String selected){page("import","API 设置","密钥验证成功后加密保存，重开应用自动读取。当前调试版本允许截图，密钥输入仍保持隐藏。");LinearLayout list=card();title(list,"配置",20);for(int i=0;i<profiles.length();i++){String n=profiles.optJSONObject(i).optString("name");button(list,(n.equals(active)?"✓ ":"")+n+(vault.has(n)?" · 密钥已保存":" · 未设置密钥"),false,()->settings(n));}button(list,"＋ 新建配置",false,()->settings(""));JSONObject p=profile(selected);LinearLayout c=card();EditText name=input(c,"配置名称",p==null?"":selected,false),base=input(c,"Base URL 或完整接口地址",p==null?"https://":p.optString("base"),false),model=input(c,"模型名称",p==null?"":p.optString("model"),false),key=input(c,"新 API Key（留空表示保留已保存密钥）","",false);key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);key.setSaveEnabled(false);key.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO);Spinner protocol=new Spinner(this);protocol.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Chat Completions","Responses"}));protocol.setSelection(p!=null&&p.optBoolean("responses")?1:0);c.addView(protocol);
        button(c,"验证、保存并切换",true,()->saveProfile(selected,name.getText().toString().trim(),base.getText().toString().trim(),model.getText().toString().trim(),key.getText().toString().trim(),protocol.getSelectedItemPosition()==1));if(p!=null&&vault.has(selected))button(c,"清除已保存密钥",false,()->new AlertDialog.Builder(this).setTitle("清除密钥？").setMessage("之后调用 AI 时需要重新输入，词库不受影响。").setNegativeButton("取消",null).setPositiveButton("清除",(d,w)->{vault.clear(selected);settings(selected);}).show());if(p!=null&&profiles.length()>1)button(c,"删除此配置",false,()->deleteProfile(selected));text(body,"页面不会显示完整密钥，日志和错误也不会包含密钥。HTTPS、Bearer Key 和 OpenAI 兼容返回是当前支持范围。",13,muted);}
    private void deleteProfile(String selected){new AlertDialog.Builder(this).setTitle("删除配置？").setMessage("不会删除词库、场景或关联。").setNegativeButton("取消",null).setPositiveButton("删除",(d,w)->{JSONArray next=new JSONArray();for(int i=0;i<profiles.length();i++)if(!selected.equals(profiles.optJSONObject(i).optString("name")))next.put(profiles.optJSONObject(i));profiles=next;vault.clear(selected);if(active.equals(selected))active=profiles.optJSONObject(0).optString("name");persistProfiles();settings(active);}).show();}
    private void saveProfile(String old,String name,String base,String model,String entered,boolean responses){try{if(name.isEmpty()||name.length()>40||model.isEmpty())throw new Exception("请填写配置名称和模型。");if(!name.equals(old)&&profile(name)!=null)throw new Exception("配置名称已存在。");ApiClient.endpoint(base,responses);String key=entered.isEmpty()?vault.get(old):entered;if(key.isEmpty())throw new Exception("首次保存必须填写 API Key。");busy=true;toast("正在验证密钥…");worker.execute(()->{try{ApiClient.verify(base,model,key,responses);vault.put(name,key);if(!old.isEmpty()&&!old.equals(name))vault.clear(old);JSONObject updated=new JSONObject().put("name",name).put("base",base).put("model",model).put("responses",responses);JSONArray next=new JSONArray();for(int i=0;i<profiles.length();i++)if(!old.equals(profiles.optJSONObject(i).optString("name")))next.put(profiles.optJSONObject(i));next.put(updated);profiles=next;active=name;persistProfiles();runOnUiThread(()->{busy=false;toast("验证成功，密钥已安全保存。");long pending=store.latestBatch();if(pending>0)resumeBatch(pending);else home();});}catch(Exception e){runOnUiThread(()->{busy=false;settings(old);message("验证失败："+safeError(e));});}});}catch(Exception e){message(e.getMessage());}}

    private static String read(InputStream in,int limit)throws Exception{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){out.write(b,0,n);if(out.size()>limit)throw new Exception("文件过大。");}return new String(out.toByteArray(),StandardCharsets.UTF_8);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;try{
        if(request==20){String raw;try(InputStream in=getContentResolver().openInputStream(data.getData())){raw=read(in,5*1024*1024);}parsePreview(raw,true,"csv");return;}
        if(request==10){JSONArray list=new JSONArray();for(JSONObject r:rows())list.put(r);try(OutputStream out=getContentResolver().openOutputStream(data.getData(),"wt")){out.write(list.toString(2).getBytes(StandardCharsets.UTF_8));}toast("已导出词库，不含 API 密钥。");}
        if(request==11){JSONArray list;try(InputStream in=getContentResolver().openInputStream(data.getData())){list=new JSONArray(read(in,5*1024*1024));}ArrayList<ContentValues> values=new ArrayList<>();for(int i=0;i<list.length();i++){JSONObject r=list.getJSONObject(i);String w=Review.normalize(r.getString("word"));JSONObject c=r.getJSONObject("content");ContentValues v=new ContentValues();v.put("word",w);v.put("content",c.toString());v.put("stage",r.optInt("stage"));v.put("due",r.optString("due",today()));v.put("mastery",r.optInt("mastery"));if(!r.optString("learned_at").isEmpty())v.put("learned_at",r.optString("learned_at"));values.add(v);}new AlertDialog.Builder(this).setTitle("导入 "+values.size()+" 个旧版词？").setMessage("同名单词保留当前记录。").setNegativeButton("取消",null).setPositiveButton("导入",(d,w)->{db.beginTransaction();try{for(ContentValues v:values)db.insertWithOnConflict("words",null,v,SQLiteDatabase.CONFLICT_IGNORE);db.setTransactionSuccessful();}finally{db.endTransaction();}library();}).show();}
    }catch(Exception e){message("文件无法读取或格式不正确，原数据未被覆盖。");}}
    @Override public void onBackPressed(){if(!"import".equals(tab))home();else super.onBackPressed();}@Override protected void onDestroy(){worker.shutdownNow();if(db!=null)db.close();super.onDestroy();}
}
